//SEM BLOCO ASSOCIADO AO IF
//AS CHAVES SÃO OPCIONAIS, MAS COM ISSO SÓ TERÁ UMA ÚNICA SENTENÇA ASSOCIADA AO BLOCO, NESTE CASO, SERÁ IMPRESSO APENAS O CONSOLE.LOG(NUM)
//É RECOMENDÁVEL SEMPRE USAR CHAVES.
function teste(num) { 
    if(num > 7)
    console.log(num)
    console.log('Final') //NESTE CASO SEMPRE SERÁ EXECUTADO, MESMO SE A CONDIÇÃO FOR TRUE OU FALSE
}

teste(8)

//NÃO USAR PONTO E VÍRGULA COM O BLOCO IF
//NESTE CASO, POR TER PONTO E VÍRGULA, O BLOCO IRÁ IGNORAR A CONDIÇÃO, IMPRIMINDO NO CONSOLE MESMO QUE DÊ FALSO OU VERDADEIRO
function teste2(num) {
    if(num > 7); {  
        console.log(num)
    }
}

teste2(10)